appName: my-weather-app

image:
  name: localhost/my_weather
  repository: somerepo
  tag: 0.0.1
  pullPolicy: Always
  pullSecret_GHCR: "github-pull-secret"
  pullSecret_ECR: "ecr-pull-secret"

replicationCount: 1

cpuRequest: "1000m"
cpuLimit: "1000m"

memRequest: "2Gi"
memLimit: "2Gi"

livenessPath: /actuator/health
livenessPort: 8181
livenessInitialDelaySeconds: 20
livenessTimeoutSeconds: 5
livenessPeriodSeconds: 10

readinessPath: /actuator/health
readinessPort: 8181
readinessInitialDelaySeconds: 20
readinessTimeoutSeconds: 5
readinessPeriodSeconds: 10

