on:
  workflow_dispatch:

env:
  REGISTRY: 'ghcr.io'
  USER: ${{ github.actor }}
  TOKEN: ${{ secrets.GK_TOKEN }}
  DOCKER_PATH: '.'
  REPO_NAME: ${{ github.repository }}


jobs:
  Docker-Build_job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: 'Login to GitHub Registry'
        run: |
          docker login ${{ env.REGISTRY }} -u ${{ env.USER }} -p ${{ env.TOKEN }}
          echo "GITHASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: 'Build Docker Image'
        run: |
          docker build ${{ env.DOCKER_PATH }} -t ${{ env.REGISTRY }}/${{ env.REPO_NAME }}:${{ env.GITHASH }}
          docker push ${{ env.REGISTRY }}/${{ env.REPO_NAME }}:${{ env.GITHASH }}
