---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello-cron
spec:
  schedule: "0/2 * * * *"
  concurrencyPolicy: "Forbid"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello-cron
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: "{{ .Values.appName }}-{{ .Values.environment }}-cron"
spec:
  schedule: "0/2 * * * *"
  concurrencyPolicy: "Forbid"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: "{{ .Values.appName }}-{{ .Values.environment }}-cron"
            image: localhost/curl-weather:0.0.2
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello World; curl wttr.in/Nashville,TN
          restartPolicy: OnFailure
          imagePullSecrets:
            - name: {{ .Values.image.pullSecret_GHCR }}