---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.appName }}-cron
spec:
  schedule: "0/2 * * * *"
  concurrencyPolicy: "Allow"
  succesfulJobHistoryLimit: 3
  failedJobHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Values.appName }}-cron
            image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
            imagePullPolicy: IfNotPresent
          restartPolicy: Never
          imagePullSecrets:
            - name: {{ .Values.image.pullSecret_GHCR }}
