---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: "{{ .Values.appName }}-{{ .Values.environment }}-cron"
  labels:
    app: "{{ .Values.appName }}"
spec:
  schedule: "0/5 * * * *"
  concurrencyPolicy: "Allow"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Values.appName }}-cron
            image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
            command:
            - /usr/local/bin/python main.py
            imagePullPolicy: IfNotPresent
          restartPolicy: Never
          imagePullSecrets:
            - name: {{ .Values.image.pullSecret_GHCR }}
