---
apiVersion: batch/v1
kind: CronJob
metadata:
  {{- with .Values.podAnnotations }}
  annotations:
    {{- toYaml . | nindent 12 }}
  {{- end }}
  labels:
    {{- include "app.selectorLabels" . | nindent 12 }}
spec:
  schedule: "0/5 * * * *"
  concurrencyPolicy: "Replace"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Values.appName }}-cron
            image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
            imagePullPolicy: IfNotPresent
          restartPolicy: Never
          imagePullSecrets:
            - name: {{ .Values.image.pullSecret_GHCR }}
